
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jun 23 12:29:30 CST 2023
//----------------------------------------------------

package Lexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INTERRUPTOR = 15;
  public static final int CASO = 16;
  public static final int Coma = 29;
  public static final int C_Llaves = 20;
  public static final int ENTERO = 2;
  public static final int SI = 5;
  public static final int Comparacion = 23;
  public static final int ENTONCES = 10;
  public static final int Menor = 36;
  public static final int FIN = 11;
  public static final int Asignacion = 22;
  public static final int Mayor = 37;
  public static final int A = 14;
  public static final int A_Parentesis = 31;
  public static final int SINO = 6;
  public static final int MIENTRAS = 8;
  public static final int Punto = 30;
  public static final int ESCRIBIR = 13;
  public static final int C_Parentesis = 32;
  public static final int Division = 27;
  public static final int EOF = 0;
  public static final int DosPuntos = 17;
  public static final int error = 1;
  public static final int ERROR = 40;
  public static final int MenorIgual = 33;
  public static final int Identificador = 38;
  public static final int Espacio = 21;
  public static final int Cierre = 28;
  public static final int Resta = 25;
  public static final int LEER = 12;
  public static final int MayorIgual = 34;
  public static final int DONDE = 9;
  public static final int PARA = 7;
  public static final int Multiplicacion = 26;
  public static final int TEXTO = 3;
  public static final int Numero = 39;
  public static final int Suma = 24;
  public static final int DEFECTO = 18;
  public static final int FLOTANTE = 4;
  public static final int A_Llaves = 19;
  public static final int Comillas = 35;
}

